/lustre/alice/users/szhu/work/Analysis/PairFlow/kit/BSMerge.exe 0.6 AssoYeild_BS_bs.root ../output/AssoYeild_BS*root
/lustre/alice/users/szhu/work/Analysis/PairFlow/kit/BSMerge.exe 0.6 AssoYeildGroupEtaGap_bInt_BS_bs.root ../output/AssoYeildGroupEtaGap_bInt_BS*root
/lustre/alice/users/szhu/work/Analysis/PairFlow/kit/BSMerge.exe 0.6 AssoYeildGroupEtaGap_bInt_f_BS_bs.root ../output/AssoYeildGroupEtaGap_bInt_f_BS*root
/lustre/alice/users/szhu/work/Analysis/PairFlow/kit/BSMerge.exe 0.6 AssoYeildGroupEtaGap_bLow_BS_bs.root ../output/AssoYeildGroupEtaGap_bLow_BS*root
/lustre/alice/users/szhu/work/Analysis/PairFlow/kit/BSMerge.exe 0.6 AssoYeildGroupEtaGap_bLow_f_BS_bs.root ../output/AssoYeildGroupEtaGap_bLow_f_BS*root
/lustre/alice/users/szhu/work/Analysis/PairFlow/kit/BSMerge.exe 0.6 AssoYeildGroupEtagapPt_bInt_BS_bs.root ../output/AssoYeildGroupEtagapPt_bInt_BS*root
/lustre/alice/users/szhu/work/Analysis/PairFlow/kit/BSMerge.exe 0.6 AssoYeildGroupEtagapPt_bInt_f_BS_bs.root ../output/AssoYeildGroupEtagapPt_bInt_f_BS*root
/lustre/alice/users/szhu/work/Analysis/PairFlow/kit/BSMerge.exe 0.6 AssoYeildGroupEtagapPt_bLow_BS_bs.root ../output/AssoYeildGroupEtagapPt_bLow_BS*root
/lustre/alice/users/szhu/work/Analysis/PairFlow/kit/BSMerge.exe 0.6 AssoYeildGroupEtagapPt_bLow_f_BS_bs.root ../output/AssoYeildGroupEtagapPt_bLow_f_BS*root
/lustre/alice/users/szhu/work/Analysis/PairFlow/kit/BSMerge.exe 0.6 AssoYeildPt_BS_bs.root ../output/AssoYeildPt_BS*root
