/lustre/alice/users/szhu/work/Analysis/PairFlow/kit/BSMerge.exe 0.6 AssoYield_BS_bs.root ../output/AssoYield_BS*root
/lustre/alice/users/szhu/work/Analysis/PairFlow/kit/BSMerge.exe 0.6 AssoYieldGroupEtaGap_bInt_BS_bs.root ../output/AssoYieldGroupEtaGap_bInt_BS*root
/lustre/alice/users/szhu/work/Analysis/PairFlow/kit/BSMerge.exe 0.6 AssoYieldGroupEtaGap_bInt_f_BS_bs.root ../output/AssoYieldGroupEtaGap_bInt_f_BS*root
/lustre/alice/users/szhu/work/Analysis/PairFlow/kit/BSMerge.exe 0.6 AssoYieldGroupEtaGap_bLow_BS_bs.root ../output/AssoYieldGroupEtaGap_bLow_BS*root
/lustre/alice/users/szhu/work/Analysis/PairFlow/kit/BSMerge.exe 0.6 AssoYieldGroupEtaGap_bLow_f_BS_bs.root ../output/AssoYieldGroupEtaGap_bLow_f_BS*root
/lustre/alice/users/szhu/work/Analysis/PairFlow/kit/BSMerge.exe 0.6 AssoYieldGroupEtagapPt_bInt_BS_bs.root ../output/AssoYieldGroupEtagapPt_bInt_BS*root
/lustre/alice/users/szhu/work/Analysis/PairFlow/kit/BSMerge.exe 0.6 AssoYieldGroupEtagapPt_bInt_f_BS_bs.root ../output/AssoYieldGroupEtagapPt_bInt_f_BS*root
/lustre/alice/users/szhu/work/Analysis/PairFlow/kit/BSMerge.exe 0.6 AssoYieldGroupEtagapPt_bLow_BS_bs.root ../output/AssoYieldGroupEtagapPt_bLow_BS*root
/lustre/alice/users/szhu/work/Analysis/PairFlow/kit/BSMerge.exe 0.6 AssoYieldGroupEtagapPt_bLow_f_BS_bs.root ../output/AssoYieldGroupEtagapPt_bLow_f_BS*root
/lustre/alice/users/szhu/work/Analysis/PairFlow/kit/BSMerge.exe 0.6 AssoYieldPt_BS_bs.root ../output/AssoYieldPt_BS*root
